spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name:
      engBoost

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yml


server:
  port:
    8014

api:
  properties:
    merriam-webster:
      url:
        ${MERRIAM_WEBSTER_URL}
      api_key:
        ${MERRIAM_WEBSTER_API_KEY}

    thesaurus:
      url:
        ${THESAURUS_URL}
      api_key:
        ${THESAURUS_API_KEY}