spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name:
      engBoost

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: true

  datasource:
  #    url: jdbc:postgresql://localhost:5432/${DB_NAME}
  #    driver-class-name: org.postgresql.Driver
  #    username: ${DB_USERNAME}
  #    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5439/mydb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        show_sql: true

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yml


logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
  file:
    name: logs/app.log
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%-5level) %clr(%logger{36}){cyan} %clr(-){faint} %clr(%msg%n){blue}"
  logback:
    rollingpolicy:
      file-name-pattern: logs/app.%d{yyyy-MM-dd}.log
      max-history: 7

server:
  port:
    8080

api:
  properties:
    merriam-webster:
      url:
        ${MERRIAM_WEBSTER_URL}
      api_key:
        ${MERRIAM_WEBSTER_API_KEY}

    thesaurus:
      url:
        ${THESAURUS_URL}
      api_key:
        ${THESAURUS_API_KEY}

security:
  jwt:
    secret: ${JWT_SECRET}
    accessDuration: ${JWT_ACCESS_DURATION}
    refreshDuration: ${JWT_REFRESH_DURATION}
